name: Action Practice


on:
  push:
  schedule:
    - cron: "0 16 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests
   #   - name: Run
     #   run: python3 ./run.py
      - name: Run-invsr
        run: python3 ./invsr.py
      - name: Run-invsr
        run: python3 ./easyocr.py

        
        
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:  /*
          draft: true

  
